.github/PULL_REQUEST_TEMPLATE.md

프로젝트의 협업 효율성을 높이기 위해 Pull Request 템플릿 파일을 추가하였습니다.

chore: PR 템플릿 파일 추가

---

.github/workflows/github-actions.yml

- 워크플로 내부 환경 변수를 참조하도록 되어 있던 부분을 올바르게 수정하였습니다.
- 자동 배포 과정에서 `dev-secure` 혹은 새롭게 설정한 프로필을 올바르게 반영하도록 수정하였습니다.
- 확인 완료되는대로 main에 병합하도록 하겠습니다.

fix: GitHub 변수 미반영 오류 수정

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/global/error_handling/ErrorResponse.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/global/result_handling/ResultResponse.kt

- 성해님이 제보해주신 에러 응답이 정상적으로 내려가지 않는 오류를 수정했습니다!
- private을 남발했더니 발생한 문제였네요... 더욱 주의하겠습니다.

fix/ 에러 응답이 정상적으로 내려가지 않는 오류 수정

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/controller/CommentController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/repository/CommentEntity.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/repository/CommentLikeEntity.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/repository/CommentLikeRepository.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/repository/CommentRepository.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/service/Comment.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/service/CommentBrief.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/service/CommentException.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/service/CommentLikeService.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/service/CommentLikeServiceImpl.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/service/CommentService.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/service/CommentServiceImpl.kt

- 포스트에 달리는 댓글 관련 기능을 구현하였습니다.
- GlobalhandleException 은 아직 적용되지 않았습니다!
- post PR과 동일한 구조를 진행하되 Mapper를 따로 분리하지 않았습니다. (재사용성이 없고, mapper에 repository 관련 로직이 들어가는 것이 적절치 않다고 판단했습니다!)

Feat/comment: 포스트 댓글 관련 기능 구현

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/global/error_handling/ErrorCode.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/global/error_handling/ErrorResponse.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/global/error_handling/GlobalExceptionHandler.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/global/result_handling/ResultResponse.kt

- 예상치 못한 서버 오류 handling 삭제(주석처리)
- 또 써야할 때가 되면 다시 부활시키겠습니다.

Fix/예상치 못한 서버 오류 handling 삭제(주석처리)

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/Waffle5gramserverApplication.kt

- 코드를 rebase merge하는 과정에서 특정 어노테이션이 2회 반복되어 어플리케이션이 실행이 안되는 오류가 있어 제거하였습니다.

!HOTFIX: 중복 어노테이션 제거

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/global/error_handling/ErrorCode.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/global/result_handling/ResultCode.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/user/controller/UserPrivateController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/user/dto/UserPrivateResponse.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/user/exception/PrivateChangeFailException.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/user/repository/UserEntity.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/user/repository/UserRepository.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/user/service/InstagramUserServiceImpl.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/user/service/UserPrivateService.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/user/service/UserPrivateServiceImpl.kt
src/test/kotlin/com/wafflestudio/toyproject/waffle5gramserver/user/UserPrivateServiceTest.kt

- 유저 공개/비공개 전환에 사용되는 api 2개를 구현했습니다. 
- JUIT으로 간단한 단위 테스트 코드를 짜서 통과 확인했습니다.
- UserEntity에서 성별 관련 항목을 수정하기 위해 빠른 리뷰 부탁드립니다!

Feat: 유저 공개/비공개 전환 api 구현

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/follow/controller/FollowController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/follow/controller/FollowRequestController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/follow/controller/FollowRetrieveController.kt

Fix / @PathVariable annotation 오류 수정

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/controller/SavedFeedController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/controller/UserFeedController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/SavedFeedService.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/SavedFeedServiceImpl.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/UserFeedService.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/UserFeedServiceImpl.kt

- feed 관련 엔드포인트를 userid를 사용하는 방식에서 username을 사용하는 방식으로 통일하였습니다.
- endpoint 수정 외에는 다른 변경 사항은 없습니다!

Refactor/feed-endpoint: feed 관련 엔드 포인트 수정

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/controller/UserFeedController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/UserFeedService.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/UserFeedServiceImpl.kt

유저 게시물 조회 관련 api 3개에 슬랙에서 언급한 내용을 수정했습니다.

Fix / UserFeedRetrieve 관련 api 3개에 로그인 유저 의존성 및 에러 추가

---

.github/workflows/github-actions.yml

test: 변경사항 생성

---

.github/workflows/github-actions.yml

fix: 도커 환경변수 및 스크립트 수정

---

.github/workflows/github-actions.yml

fix: mysql 데이터베이스 생성

---

.github/workflows/github-actions.yml

HOTFIX: 데이터베이스 생성 및 도커 실행 커맨드 수정

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/auth/SecurityConfig.kt

- 원격 h2 콘솔 접속 문제 해결을 위해 dev-secure에서 cors disable
- prod 프로필을 위한 filterChain을 분리하여 h2 dependency를 제거하고 CORS 설정 주입

fix: filterChain prod와 dev-secure 구분

---

.github/workflows/github-actions.yml

test: 변경 사항 생성

---

.github/workflows/github-actions.yml
src/main/resources/application-prod.yaml

Test: 데이터베이스 접근 후 테이블 생성

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/controller/CommentController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/service/Comment.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/service/CommentLikeServiceImpl.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/service/CommentService.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/service/CommentServiceImpl.kt

- CommentDTO에 liked field 추가했습니다!
-

feat: CommentDTO에 liked field 추가

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/post/controller/PostController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/post/repository/PostSaveEntity.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/post/service/PostSaveServiceImpl.kt

- PostController에서 save 기능 관련 엔드포인트의 오탈자를 수정하였습니다.
- postSaveEntity를 BaseAuditingEntity를 상속받도록 수정하였습니다.

Fix/post-save-not-found: Post Save 기능 엔드 포인트 오타 수정

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/comment/controller/CommentController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/reply/controller/ReplyController.kt

Fix/add-request-body-dto: request body DTO를 추가

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/profile/controller/ProfileController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/profile/service/ProfileService.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/profile/service/ProfileServiceImpl.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/user/repository/UserLinkRepository.kt

-  Profile link에서 Put api를 구현하였습니다.
- 테스트는 따로 작성하지 않았습니다.

Feat : Profile link에서 Put api 구현

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/global/error_handling/ErrorCode.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/post/service/PostImageServiceImpl.kt

Hotfix/threads: 스레드 조기 종료 에러 수정

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/reply/controller/ReplyController.kt

- delete-reply-endpoint를 수정
-
-

fix: delete-reply-endpoint를 수정

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/post/controller/PostController.kt
src/main/resources/application-dev-secure.yaml

fix: category 요청 타입 변경

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/profile/service/ProfileServiceImpl.kt

fix: 프로필 삭제 시 기본 이미지 url 반환

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/global/error_handling/ErrorCode.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/profile/mapper/ProfileResponseMapper.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/search/controller/SearchController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/search/dto/MiniProfilePageResponse.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/search/dto/RecentSearch.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/search/dto/RecentSearchResponse.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/search/mapper/ToRecentSearch.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/search/repository/RecentSearchEntity.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/search/repository/RecentSearchRepository.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/search/service/SearchService.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/search/service/SearchServiceImpl.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/user/repository/UserRepository.kt

- 인물 검색 기능을 구현했습니다.
- 프로젝트 마감 기한이 다가와서 프론트 단에서 빠른 테스팅이 필요하므로, 리뷰 기간 없이 바로 머지하겠습니다.
- 따로 작성한 테스트는 없으며, 프론트 단에서 테스트하면서 실시간으로 수정할 예정입니다.

Feat : 인물 검색 기능 구현

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/controller/FeedController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/controller/FeedPreviewResponse.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/controller/FeedResponse.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/controller/SavedFeedController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/controller/UserFeedController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/SavedFeedService.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/SavedFeedServiceImpl.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/UserFeedService.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/UserFeedServiceImpl.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/post/repository/PostMediaRepository.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/post/repository/PostRepository.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/post/repository/PostSaveRepository.kt

- #21에 해당하는 user, save 관련 피드에서 newer, older endpoint를 통합하였습니다!

Feat/feed-get-api: feed 관련 api 통합

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/controller/SavedFeedController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/controller/UserFeedController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/SavedFeedService.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/SavedFeedServiceImpl.kt

Fix/delete-notused-import: 사용하지 않는 import 문을 제거

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/controller/SavedFeedController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/controller/UserFeedController.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/SavedFeedService.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/SavedFeedServiceImpl.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/UserFeedService.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/UserFeedServiceImpl.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/post/repository/PostRepository.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/post/repository/PostSaveRepository.kt

- FeedResponse를 Slice가 아닌 List를 사용하도록 변경하였습니다.

feat: FeedResponse를 Slice가 아닌 List를 사용하도록 변경

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/auth/service/UserAuthServiceImpl.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/search/dto/RecentSearchResponse.kt

Fix: 회원 가입 시 기본 프로필 이미지 적용

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/search/dto/RecentSearchResponse.kt
src/main/resources/application-prod.yaml

Feat/production: prod 프로필 배포

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/UserFeedServiceImpl.kt

- 프로필 페이지에 본인이 들어갔을 경우 피드를 반환하도록 설정하였습니다

feat: 프로필 페이지에 본인이 들어갔을 경우 피드를 반환하도록 설정

---

src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/search/service/SearchServiceImpl.kt
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/user/repository/UserRepository.kt

fix : 의심되는 오류 수정안

---

README.md
src/main/kotlin/com/wafflestudio/toyproject/waffle5gramserver/feed/service/UserFeedServiceImpl.kt

- userFeed에서 isliked 필드 오류 해결했습니다.

Fix/user-feed-isliked-error: userFeed에서 isliked 필드 오류 해결
